# LLM Settings
Gemini_API_KEY = "YOUR_GEMINI_API_KEY"
VERTX_API_TOKEN = "YOUR_VERTX_API_TOKEN"
BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai/"
Gemini_API_KEY_2 = "YOUR_GEMINI_API_KEY_2"
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
tool_agent_model = "gemini-2.0-flash"
main_agent_model = "gpt-4o-mini"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
PLATFORM = "openai"
main_model_type = "gpt-4o-mini"
extra_model_type = "gemini-2.0-flash"
divider_model_type = "gpt-4o-mini"
extract_model_type = "gemini-1.5-flash"

# Credentials and App Settings
GOOGLE_APPLICATION_CREDENTIALS = "Config/gcp_creds.json"
VERIFY_TOKEN = "YOUR_VERIFY_TOKEN"
PROJECT_ID = "YOUR_PROJECT_ID"
WHATSAPP_PHONE_NUMBER_ID = "YOUR_PHONE_NUMBER_ID"
Phone_number = "YOUR_PHONE_NUMBER"
firebase_path = "Config/firebase.json"
WHATSAPP_ACCESS_TOKEN = "YOUR_WHATSAPP_ACCESS_TOKEN"
PAGE_ACCESS_TOKEN = "YOUR_PAGE_ACCESS_TOKEN"
odoo_url = "https://your-odoo-instance.odoo.com"
odoo_db = "your-database-name"
odoo_email = "your-email@example.com"
odoo_password = "your-password"
encrypt_secert_key = "YOUR_ENCRYPTION_SECRET_KEY"
cloud_url = "https://your-cloud-run-url.run.app"
audio_url = "https://your-cloud-run-url.run.app/get_audio"
image_url = "https://your-cloud-run-url.run.app/get_image"
temp_folder = "./temp"
DEFUALT_USER_DB_NAME = "user-messages"
DEFUALT_MESSAGES_POOL_DB_NAME = "messages-pool"
DEFAULT_BILLING_POOL_DB_NAME = "billing-pool"

# RAG Settings
RAG_DB = "YourBigQueryDataset"
RAG_TABLE = "YourBigQueryTable"
FEW_SHOTS_TABLE = "YourFewShotsTable"
FEW_SHOTS_SCHEMA_PATH = "Config/few_shots_rag_schema.json"
INFO_SCHEMA_PATH = "Config/rag_schema.json"
